= Lambda Custom Runtime (not yet released)

The Paketo Buildpack for AWS Lambda Custom Runtime is a Cloud Native Buildpack that provides a custom runtime to run your application as Lambda function.

== Behavior

It will participate if one of the following conditions are met:

* The `$BP_LAMBDA_CUSTOM_RUNTIME` and  the `$BP_NATIVE_IMAGE` environment variables are set to a truthy value (i.e. `true`, `t`, `1` ignoring case)

The buildpack will do the following for the Java Native application:

* Uses the binary generated by the native-image buildpack locaretd in the `/workspace` directory to contribute to the `custom-runtime` process type.

When `$BP_LAMBDA_CUSTOM_RUNTIME_INTERFACE_EMULATOR` is set to `true`, the buildpack will also do the following:

* Contributes the `aws-lambda-rie` binary to the `emulator` layer.

* Contribtues the `emulator` process type.


== Configuration

The buildpack can be configured using environment variables:

* `$BP_LAMBDA_CUSTOM_RUNTIME` - Set to `true` to enable the buildpack. Default is `false`.

* `$BP_LAMBDA_CUSTOM_RUNTIME_INTERFACE_EMULATOR` - Set to `true` to enable the emulator. Default is `false`.


== License

This buildpack is released under version 2.0 of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0).